// client/src/pages/Main/Sidebar/index.tsx
import React, { useContext } from 'react';
import ActiveTagContext from '#/contexts/ActiveTagContext';
import { Tag } from '#/types/api.types';
import { css } from 'linaria';
import TagItem from './TagItem';
import { Link, useLocation } from 'react-router-dom';
import cn from 'classnames';

interface Props {
  tags: Array<Tag>;
}

const Sidebar: React.FC<Props> = props => {
  const { activeTag, setActiveTag } = useContext(ActiveTagContext);

  const onItemClick = (tag: Tag) => {
    setActiveTag(tag);
  };

  const location = useLocation();
  const isActive = location.pathname === '/all-feeds';

  return (
    <div className={wrapperClass}>
      <Link to="/all-feeds">
        <div
          className={cn('button', 'is-primary', {
            'is-light': !isActive,
          })}
        >
          All Feeds
        </div>
      </Link>
      {props.tags.map(tag => {
        const isActive = tag.id === activeTag?.id;

        return (
          <TagItem
            tag={tag}
            onClick={onItemClick}
            isActive={isActive}
            key={tag.id}
          />
        );
      })}
    </div>
  );
};

const wrapperClass = css`
  width: 8rem;
`;

export default Sidebar;

// client-vue/src/pages/Main/Sidebar/index.vue
<template>
  <div>
    <a class="button is-primary" :class="isAllFeeds">All Feeds</a>
    <TagItem
      v-for="tag in tags"
      :key="tag.id"
      :tag="tag"
      :isActive="tag.id === activeTagId"
      :onClick="onTagClick"
    />
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import store from '@/store';
import { Tag } from '@/types/api';
import TagItem from './TagItem.vue';

export default Vue.extend({
  name: 'Sidebar',
  components: { TagItem },

  props: {
    tags: Array,
  },

  data() {
    return {
      isAllFeeds: true,
    };
  },

  computed: {
    activeTagId: () => store.state.tags.active?.id,
  },

  methods: {
    onTagClick(tag: Tag) {
      store.commit.tags.setActiveTag(tag);
    },
  },
});
</script>

<style scoped></style>
