// client-vue/src/pages/Main/index.vue
<template>
  <div>
    <Navbar />
    <div class="content">
      <div class="is-hidden-mobile">
        <Sidebar />
      </div>
      <div class="pane-wrapper">
        <PostsPane />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

import Navbar from './Navbar.vue';
import Sidebar from './Sidebar.vue';

export default Vue.extend({
  name: 'Main',
  components: { Navbar },
});
</script>

<style lang="scss" scoped>
.content {
  display: flex;
  justify-content: center;
  margin-top: 2rem;
}

.pane-wrapper {
  width: 100%;
  max-width: 45rem;
}
</style>

// client/src/pages/Main/index.tsx
import React from 'react';
import Navbar from './Navbar';
import { ActiveTagProvider } from '#/contexts/ActiveTagContext';
import Sidebar from './Sidebar';
import { css } from 'linaria';
import * as panes from './panes';

import { Switch, Route, RouteComponentProps } from 'react-router-dom';

interface Props extends RouteComponentProps { }

const Main: React.FC<Props> = (props) => {
  return (
    <ActiveTagProvider>
      <Navbar />
      <div className={Content}>
        <div className="is-hidden-mobile">
          <Sidebar />
        </div>
        <div className={Pane}>
          <Switch>
            <Route path="/all-feeds" component={panes.FeedsManager} />
            <Route path="/" component={panes.PostsPane} />
          </Switch>
        </div>
      </div>
    </ActiveTagProvider>
  );
};

const Content = css`
  display: flex;
  justify-content: center;
  margin-top: 2rem;
`;

const Pane = css`
  width: 100%;
  max-width: 45rem;
`;

export default Main;
