// client-vue/src/pages/Main/Sidebar/TagItem.vue
<template>
  <div class="wrapper" :class="{ active: isActive }" @click="onClick(tag)">
    <span class="active-icon">#</span>
    {{ tag.name }}
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
export default Vue.extend({
  props: {
    isActive: Boolean,
    onClick: Function,
    tag: Object,
  },
});
</script>

<style lang="scss" scoped>
.wrapper {
  font-family: 'iosevka';
  white-space: nowrap;
  text-overflow: ellipsis;
  cursor: pointer;
  padding: 4px;

  &:hover {
    color: var(--primary);
  }

  &.active {
    color: var(--primary);
    font-style: italic;

    .active-icon {
      opacity: 1;
    }
  }
}

.active-icon {
  opacity: 0;
}
</style>

// client/src/pages/Home/Sidebar/TagItem.tsx
import React from 'react';
import { Tag } from '#/types/api.types';
import { css } from 'linaria';
import cn from 'classnames';

interface Props {
  isActive: boolean;
  onClick: (tag: Tag) => void;
  tag: Tag;
}

const TagItem: React.FC<Props> = ({ tag, onClick, isActive }) => {
  const handleClick = () => {
    onClick(tag);
  };

  return (
    <div
      className={cn({ [wrapperClass]: true, [activeClass]: isActive })}
      onClick={handleClick}
    >
      <span className={activeIconClass}>#</span>
      {tag.name}
    </div>
  );
};

const wrapperClass = css`
  font-family: 'iosevka';
  white-space: nowrap;
  text-overflow: ellipsis;
  cursor: pointer;
  padding: 4px;

  &:hover {
    color: var(--primary);
  }
`;

const activeIconClass = css`
  opacity: 0;
`;

const activeClass = css`
  color: var(--primary);
  font-style: italic;

  .${activeIconClass} {
    opacity: 1;
  }
`;

export default TagItem;
